print multiples of 3 upto 200 using a list

In [ ]:
print([x for x in range(3,200+1,3)])

[3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99, 102, 105, 108, 111, 114, 117, 120, 123, 126, 129, 132, 135, 138, 141, 144, 147, 150, 153, 156, 159, 162, 165, 168, 171, 174, 177, 180, 183, 186, 189, 192, 195, 198]

print the nos only divisable by 5 and 7 between 1000 and 2000 using a list( both inclusive)

In [ ]:
print([i for i in range(1000,2001) if i%5==0 and i%7==0])

[1015, 1050, 1085, 1120, 1155, 1190, 1225, 1260, 1295, 1330, 1365, 1400, 1435, 1470, 1505, 1540, 1575, 1610, 1645, 1680, 1715, 1750, 1785, 1820, 1855, 1890, 1925, 1960, 1995]

Add the n number of names in a list and print them alphabetically and reverse alphabetically.

In [ ]:
lst=[input(x) for i in range(int(input("Enter n")))]
lst.sort()
print(lst)
lst.sort(reverse=True)
print(lst)

Enter n4
surat
mangalore
manoj
ravi
['mangalore', 'manoj', 'ravi', 'surat']
['surat', 'ravi', 'manoj', 'mangalore']

Print  perfect squares and divisible by 5 between 500 and 1000( (both inclusive) using list

In [ ]:
import math
print([i for i in range(500,1001) if i%5==0 and (math.sqrt(i) - math.floor(math.sqrt(i))) == 0])

[625, 900]